version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    restart: always
    ports:
      - "8081:80"
    networks:
      - frontend

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    env_file: ./backend/.env
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    ports:
      - "4000:5000"
    depends_on:
      - postgres
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
  frontend:
